/* ============================================================
 * Smart Mummy — 宝宝辅食菜谱数据库（1岁以上）
 * ------------------------------------------------------------
 * 约定（务必遵守）：
 * 1. 每道菜谱 = 1 个宝宝 1 餐份，数量不随人数缩放（scaledQty 直接返回基准量）。
 * 2. 食材数量一律用"个数"，禁用克/斤等重量单位。
 * 3. 印尼语量词存在 INGREDIENT_PRESETS.unitId：butir(蛋/圆形)、ekor(鱼虾整只)、
 *    buah(蔬果个体)、siung(蒜瓣)、batang(长条)、potong(肉块)、lembar(片)、
 *    ikat(一把)、mangkuk(碗)、keping(面饼/束)、ruas(姜块)。
 * 4. 步骤 textId 里的 {食材key} 会在渲染时替换成"数量+量词+印尼语名"，
 *    textZh 同理，保证文字和长图一致。
 * 5. 步骤写给理解力有限的读者：一句一个动作，有具体数量、火候、分钟数。
 * 6. 辅食原则：蒸/煮/炖为主，不加酱油、糖、辣椒；1岁后可加少量盐；
 *    鱼类必须两次检查鱼刺；高致敏食材标注 allergens。
 * 7. minMonth：适合的最小月龄（12/18/24），app 按月龄过滤菜谱。
 * 8. category：staple(主食粥面)/fish/shrimp/egg/chicken/pork/beef/tofu/veg/soup。
 * ============================================================ */

/* ---------- 食材预设表（库存选择器用，双语显示） ---------- */
const INGREDIENT_PRESETS = [
  { key: 'rice',          emoji: '🍚', nameZh: '大米',   nameId: 'beras',            unitId: 'mangkuk', unitZh: '碗' },
  { key: 'millet',        emoji: '🌾', nameZh: '小米',   nameId: 'milet',            unitId: 'mangkuk', unitZh: '碗' },
  { key: 'baby_noodles',  emoji: '🍜', nameZh: '碎碎面', nameId: 'mie bayi',         unitId: 'keping',  unitZh: '束' },
  { key: 'farfalle',      emoji: '🦋', nameZh: '蝴蝶面', nameId: 'pasta kupu-kupu',  unitId: 'buah',    unitZh: '个' },
  { key: 'oats',          emoji: '🥣', nameZh: '燕麦',   nameId: 'oat',              unitId: 'mangkuk', unitZh: '碗' },
  { key: 'flour',         emoji: '🌾', nameZh: '面粉',   nameId: 'tepung terigu',    unitId: 'mangkuk', unitZh: '碗' },
  { key: 'egg',           emoji: '🥚', nameZh: '鸡蛋',   nameId: 'telur',            unitId: 'butir',   unitZh: '个' },
  { key: 'cod',           emoji: '🐟', nameZh: '鳕鱼',   nameId: 'ikan kod',         unitId: 'potong',  unitZh: '块' },
  { key: 'salmon',        emoji: '🐟', nameZh: '三文鱼', nameId: 'ikan salmon',      unitId: 'potong',  unitZh: '块' },
  { key: 'shrimp',        emoji: '🦐', nameZh: '虾',     nameId: 'udang',            unitId: 'ekor',    unitZh: '只' },
  { key: 'chicken',       emoji: '🐔', nameZh: '鸡肉',   nameId: 'daging ayam',      unitId: 'potong',  unitZh: '块' },
  { key: 'beef',          emoji: '🐮', nameZh: '牛肉',   nameId: 'daging sapi',      unitId: 'potong',  unitZh: '块' },
  { key: 'pork',          emoji: '🐷', nameZh: '猪肉',   nameId: 'daging babi',      unitId: 'potong',  unitZh: '块' },
  { key: 'pork_liver',    emoji: '🐷', nameZh: '猪肝',   nameId: 'hati babi',        unitId: 'potong',  unitZh: '块' },
  { key: 'tofu',          emoji: '🫘', nameZh: '豆腐',   nameId: 'tahu',             unitId: 'potong',  unitZh: '块' },
  { key: 'pumpkin',       emoji: '🎃', nameZh: '南瓜',   nameId: 'labu',             unitId: 'potong',  unitZh: '块' },
  { key: 'sweet_potato',  emoji: '🍠', nameZh: '红薯',   nameId: 'ubi jalar',        unitId: 'buah',    unitZh: '个' },
  { key: 'potato',        emoji: '🥔', nameZh: '土豆',   nameId: 'kentang',          unitId: 'buah',    unitZh: '个' },
  { key: 'carrot',        emoji: '🥕', nameZh: '胡萝卜', nameId: 'wortel',           unitId: 'buah',    unitZh: '根' },
  { key: 'broccoli',      emoji: '🥦', nameZh: '西兰花', nameId: 'brokoli',          unitId: 'buah',    unitZh: '个' },
  { key: 'spinach',       emoji: '🥬', nameZh: '菠菜',   nameId: 'bayam',            unitId: 'ikat',    unitZh: '把' },
  { key: 'pakcoy',        emoji: '🥬', nameZh: '小白菜', nameId: 'pakcoy',           unitId: 'buah',    unitZh: '棵' },
  { key: 'tomato',        emoji: '🍅', nameZh: '番茄',   nameId: 'tomat',            unitId: 'buah',    unitZh: '个' },
  { key: 'mushroom',      emoji: '🍄', nameZh: '香菇',   nameId: 'jamur',            unitId: 'buah',    unitZh: '个' },
  { key: 'corn',          emoji: '🌽', nameZh: '玉米',   nameId: 'jagung',           unitId: 'buah',    unitZh: '根' },
  { key: 'winter_melon',  emoji: '🍈', nameZh: '冬瓜',   nameId: 'bligo',            unitId: 'potong',  unitZh: '块' },
  { key: 'yam',           emoji: '🍠', nameZh: '山药',   nameId: 'ubi cina',         unitId: 'potong',  unitZh: '段' },
  { key: 'zucchini',      emoji: '🥒', nameZh: '西葫芦', nameId: 'zukini',           unitId: 'buah',    unitZh: '个' },
  { key: 'laver',         emoji: '🌊', nameZh: '紫菜',   nameId: 'rumput laut kering', unitId: 'lembar', unitZh: '张' },
  { key: 'avocado',       emoji: '🥑', nameZh: '牛油果', nameId: 'alpukat',          unitId: 'buah',    unitZh: '个' },
  { key: 'banana',        emoji: '🍌', nameZh: '香蕉',   nameId: 'pisang',           unitId: 'buah',    unitZh: '根' },
  { key: 'apple',         emoji: '🍎', nameZh: '苹果',   nameId: 'apel',             unitId: 'buah',    unitZh: '个' },
  { key: 'garlic',        emoji: '🧄', nameZh: '大蒜',   nameId: 'bawang putih',     unitId: 'siung',   unitZh: '瓣', seasoning: true },
  { key: 'ginger',        emoji: '🫚', nameZh: '姜',     nameId: 'jahe',             unitId: 'ruas',    unitZh: '块', seasoning: true },
  { key: 'scallion',      emoji: '🧅', nameZh: '葱',     nameId: 'daun bawang',      unitId: 'batang',  unitZh: '根', seasoning: true },
];

/* ---------- 默认家里常备，不计入库存 ---------- */
const ALWAYS_HAVE = [
  { nameZh: '辅食油（核桃油/橄榄油）', nameId: 'minyak goreng' },
  { nameZh: '盐（1岁以上少量）',      nameId: 'garam' },
  { nameZh: '姜',                    nameId: 'jahe' },
  { nameZh: '葱',                    nameId: 'daun bawang' },
  { nameZh: '柠檬（去腥）',           nameId: 'jeruk nipis' },
  { nameZh: '淀粉',                  nameId: 'tepung maizena' },
];

/* ---------- 过敏原标签（v1 只展示，不做排敏跟踪） ---------- */
const ALLERGENS = {
  egg:    { zh: '蛋',   id: 'telur',   emoji: '🥚' },
  fish:   { zh: '鱼',   id: 'ikan',    emoji: '🐟' },
  shrimp: { zh: '虾',   id: 'udang',   emoji: '🦐' },
  wheat:  { zh: '麸质', id: 'gandum',  emoji: '🌾' },
  soy:    { zh: '大豆', id: 'kedelai', emoji: '🫘' },
  nut:    { zh: '坚果', id: 'kacang',  emoji: '🥜' },
  milk:   { zh: '奶',   id: 'susu',    emoji: '🥛' },
};

/* ---------- 数量：辅食每道菜谱就是1个宝宝1餐份，不做人数缩放 ---------- */
function scaledQty(baseQty, _persons) {
  return Math.max(1, Number(baseQty) || 1);
}

/* ---------- 印尼语数量文本："2 potong labu" ---------- */
function formatQtyId(key, qty) {
  const ing = INGREDIENT_PRESETS.find(i => i.key === key);
  if (!ing) return qty + ' ' + key;
  return qty + ' ' + ing.unitId + ' ' + ing.nameId;
}

/* ---------- 渲染单步：把 {key} 换成数量文本 ---------- */
function renderStepId(recipe, step, persons) {
  return step.textId.replace(/\{(\w+)\}/g, (m, key) => {
    const found = recipe.ingredients.find(i => i.key === key);
    const base = found ? found.qty : 1;
    return formatQtyId(key, scaledQty(base, persons));
  });
}

/* ---------- 中文数量文本："2块南瓜" ---------- */
function formatQtyZh(key, qty) {
  const ing = INGREDIENT_PRESETS.find(i => i.key === key);
  if (!ing) return qty + '个' + key;
  return qty + ing.unitZh + ing.nameZh;
}

/* ---------- 渲染单步中文：同 renderStepId ---------- */
function renderStepZh(recipe, step, persons) {
  return step.textZh.replace(/\{(\w+)\}/g, (m, key) => {
    const found = recipe.ingredients.find(i => i.key === key);
    const base = found ? found.qty : 1;
    return formatQtyZh(key, scaledQty(base, persons));
  });
}

/* ---------- 菜谱 ---------- */
const RECIPES = [
  {
    id: 'pumpkin-millet-congee',
    nameZh: '南瓜小米粥',
    nameId: 'Bubur Milet Labu',
    emoji: '🎃',
    category: 'staple',
    timeMin: 35,
    difficulty: 1,
    minMonth: 12,
    allergens: [],
    ingredients: [
      { key: 'millet',  qty: 1 },
      { key: 'pumpkin', qty: 2 },
    ],
    steps: [
      { emoji: '🌾', textId: 'Cuci {millet} 2 kali dengan air bersih.', textZh: '{millet}用清水洗2遍。' },
      { emoji: '🎃', textId: 'Kupas {pumpkin}, potong dadu kecil (1 cm).', textZh: '{pumpkin}去皮，切成1厘米的小丁。' },
      { emoji: '💧', textId: 'Masukkan millet dan 4 mangkuk air ke panci.', textZh: '小米和4碗水放进锅里。' },
      { emoji: '🔥', textId: 'Masak dengan api besar sampai mendidih, lalu kecilkan api.', textZh: '大火煮开后转小火。' },
      { emoji: '🎃', textId: 'Masukkan labu. Masak 25 menit. Aduk setiap 5 menit.', textZh: '放入南瓜，煮25分钟，每5分钟搅一下。' },
      { emoji: '🥄', textId: 'Labu sudah lembek? Tekan dengan sendok sampai hancur.', textZh: '南瓜软烂后，用勺子压碎。' },
      { emoji: '🍽️', textId: 'Matikan api. Tunggu sampai hangat, baru berikan ke bayi.', textZh: '关火，晾到温热再给宝宝吃。' },
    ],
    tipId: 'Kalau terlalu kental, tambah sedikit air panas.',
    tipZh: '太稠就加点热水调稀。',
  },
  {
    id: 'sweet-potato-congee',
    nameZh: '红薯大米粥',
    nameId: 'Bubur Nasi Ubi Jalar',
    emoji: '🍠',
    category: 'staple',
    timeMin: 40,
    difficulty: 1,
    minMonth: 12,
    allergens: [],
    ingredients: [
      { key: 'rice',         qty: 1 },
      { key: 'sweet_potato', qty: 1 },
    ],
    steps: [
      { emoji: '🍚', textId: 'Cuci {rice} 2 kali dengan air bersih.', textZh: '{rice}用清水洗2遍。' },
      { emoji: '🍠', textId: 'Kupas {sweet_potato}, potong dadu kecil (1 cm).', textZh: '{sweet_potato}去皮，切成1厘米的小丁。' },
      { emoji: '💧', textId: 'Masukkan beras dan 5 mangkuk air ke panci. Masak api besar sampai mendidih.', textZh: '大米加5碗水，大火煮开。' },
      { emoji: '🔥', textId: 'Kecilkan api. Masukkan ubi. Masak 30 menit, aduk setiap 5 menit.', textZh: '转小火，放红薯煮30分钟，每5分钟搅一下。' },
      { emoji: '🥄', textId: 'Tekan ubi dengan sendok sampai hancur.', textZh: '用勺子把红薯压碎。' },
      { emoji: '🍽️', textId: 'Matikan api. Tunggu sampai hangat, baru berikan ke bayi.', textZh: '关火，晾到温热再给宝宝吃。' },
    ],
    tipId: 'Pilih ubi yang manis. Tidak perlu tambah gula.',
    tipZh: '选甜一点的红薯，不用加糖。',
  },
  {
    id: 'chicken-carrot-congee',
    nameZh: '鸡肉胡萝卜粥',
    nameId: 'Bubur Ayam Wortel',
    emoji: '🥕',
    category: 'staple',
    timeMin: 40,
    difficulty: 1,
    minMonth: 12,
    allergens: [],
    ingredients: [
      { key: 'rice',    qty: 1 },
      { key: 'chicken', qty: 1 },
      { key: 'carrot',  qty: 1 },
      { key: 'ginger',  qty: 1 },
    ],
    steps: [
      { emoji: '🍚', textId: 'Cuci {rice} 2 kali dengan air bersih.', textZh: '{rice}用清水洗2遍。' },
      { emoji: '🔪', textId: 'Potong {chicken} kecil-kecil, lalu cincang sampai halus.', textZh: '{chicken}切小块，再剁成肉末。' },
      { emoji: '🥕', textId: 'Kupas {carrot}, potong dadu kecil (1 cm).', textZh: '{carrot}去皮，切成1厘米的小丁。' },
      { emoji: '💧', textId: 'Masukkan beras, 5 mangkuk air, dan {ginger} ke panci. Masak api besar sampai mendidih.', textZh: '大米加5碗水和{ginger}，大火煮开。' },
      { emoji: '🔥', textId: 'Kecilkan api. Masukkan wortel dan ayam. Masak 30 menit. Aduk setiap 5 menit supaya ayam tidak menggumpal.', textZh: '转小火，放胡萝卜和鸡肉末，煮30分钟，每5分钟搅一下防止肉末结块。' },
      { emoji: '🫚', textId: 'Ambil jahe, buang.', textZh: '挑出姜片扔掉。' },
      { emoji: '🍽️', textId: 'Matikan api. Tunggu sampai hangat, baru berikan ke bayi.', textZh: '关火，晾到温热再给宝宝吃。' },
    ],
    tipId: 'Ayam harus dicincang halus supaya bayi mudah menelan.',
    tipZh: '鸡肉要剁得够细，宝宝才好吞咽。',
  },
  {
    id: 'cod-veg-congee',
    nameZh: '鳕鱼蔬菜粥',
    nameId: 'Bubur Ikan Kod Sayur',
    emoji: '🐟',
    category: 'staple',
    timeMin: 40,
    difficulty: 1,
    minMonth: 12,
    allergens: ['fish'],
    ingredients: [
      { key: 'rice',   qty: 1 },
      { key: 'cod',    qty: 1 },
      { key: 'pakcoy', qty: 1 },
      { key: 'ginger', qty: 1 },
    ],
    steps: [
      { emoji: '🍚', textId: 'Cuci {rice}. Masak dengan 5 mangkuk air dan {ginger} selama 25 menit.', textZh: '{rice}洗净，加5碗水和{ginger}煮25分钟。' },
      { emoji: '🐟', textId: 'Raba {cod} dengan tangan. Cabut semua tulang. Periksa 2 kali!', textZh: '用手仔细摸{cod}，拔掉所有鱼刺。检查2遍！' },
      { emoji: '🔪', textId: 'Potong ikan kecil-kecil (1 cm).', textZh: '鱼肉切成1厘米的小丁。' },
      { emoji: '🥬', textId: 'Cuci {pakcoy}, potong halus.', textZh: '{pakcoy}洗净，切碎。' },
      { emoji: '🔥', textId: 'Masukkan ikan ke bubur. Masak 5 menit.', textZh: '鱼丁放进粥里，煮5分钟。' },
      { emoji: '🥬', textId: 'Masukkan sayur. Masak 2 menit. Ambil jahe, buang.', textZh: '放菜碎煮2分钟，挑出姜片扔掉。' },
      { emoji: '🍽️', textId: 'Matikan api. Tunggu sampai hangat, baru berikan ke bayi.', textZh: '关火，晾到温热再给宝宝吃。' },
    ],
    tipId: 'Tulang ikan harus diperiksa 2 kali — ini langkah paling penting!',
    tipZh: '鱼刺一定要检查两遍，这是最重要的一步！',
  },
  {
    id: 'tomato-beef-noodles',
    nameZh: '番茄牛肉碎碎面',
    nameId: 'Mie Bayi Tomat Daging Sapi',
    emoji: '🍅',
    category: 'staple',
    timeMin: 25,
    difficulty: 1,
    minMonth: 12,
    allergens: ['wheat'],
    ingredients: [
      { key: 'baby_noodles', qty: 1 },
      { key: 'beef',         qty: 1 },
      { key: 'tomato',       qty: 1 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Cincang {beef} sampai halus.', textZh: '{beef}剁成肉末。' },
      { emoji: '🍅', textId: 'Rebus {tomato} di air panas 1 menit. Kupas kulitnya. Potong kecil-kecil.', textZh: '{tomato}用开水烫1分钟，去皮切碎。' },
      { emoji: '🔥', textId: 'Panaskan 1 sendok teh minyak. Masukkan daging. Masak 3 menit.', textZh: '热锅放1茶勺油，下牛肉末炒3分钟。' },
      { emoji: '🍅', textId: 'Masukkan tomat. Masak 3 menit sampai lembek.', textZh: '下番茄炒3分钟，炒到软烂。' },
      { emoji: '💧', textId: 'Tambah 2 mangkuk air. Masak sampai mendidih.', textZh: '加2碗水，煮开。' },
      { emoji: '🍜', textId: 'Patahkan {baby_noodles} jadi pendek (2 cm). Masukkan ke panci. Masak 5 menit sampai lembek.', textZh: '{baby_noodles}掰成2厘米的小段下锅，煮5分钟至软烂。' },
      { emoji: '🍽️', textId: 'Matikan api. Tunggu sampai hangat, baru berikan ke bayi.', textZh: '关火，晾到温热再给宝宝吃。' },
    ],
    tipId: 'Mie harus benar-benar lembek — tes dengan sendok, harus mudah dipotong.',
    tipZh: '面要煮到用勺子能轻松压断的程度。',
  },
  {
    id: 'spinach-egg-noodles',
    nameZh: '菠菜鸡蛋面',
    nameId: 'Mie Bayam Telur',
    emoji: '🥬',
    category: 'staple',
    timeMin: 15,
    difficulty: 1,
    minMonth: 12,
    allergens: ['egg', 'wheat'],
    ingredients: [
      { key: 'baby_noodles', qty: 1 },
      { key: 'egg',          qty: 1 },
      { key: 'spinach',      qty: 1 },
    ],
    steps: [
      { emoji: '🥬', textId: 'Cuci {spinach}. Rebus di air mendidih 1 menit. Angkat, potong halus.', textZh: '{spinach}洗净，开水焯1分钟，捞出切碎。' },
      { emoji: '🥚', textId: 'Kocok {egg} di mangkuk dengan garpu.', textZh: '{egg}用叉子打散。' },
      { emoji: '💧', textId: 'Rebus 2 mangkuk air sampai mendidih.', textZh: '2碗水烧开。' },
      { emoji: '🍜', textId: 'Patahkan {baby_noodles} jadi pendek. Masukkan ke air mendidih. Masak 4 menit.', textZh: '{baby_noodles}掰短下锅，煮4分钟。' },
      { emoji: '🥚', textId: 'Tuang telur pelan-pelan sambil diaduk, jadi bunga telur.', textZh: '慢慢倒入蛋液，边倒边搅，成蛋花。' },
      { emoji: '🥬', textId: 'Masukkan bayam. Masak 1 menit.', textZh: '放菠菜碎煮1分钟。' },
      { emoji: '🍽️', textId: 'Matikan api. Tunggu sampai hangat, baru berikan ke bayi.', textZh: '关火，晾到温热再给宝宝吃。' },
    ],
    tipId: 'Bayam direbus dulu supaya tidak pahit.',
    tipZh: '菠菜先焯水，去掉涩味。',
  },
  {
    id: 'yam-millet-congee',
    nameZh: '山药小米粥',
    nameId: 'Bubur Milet Ubi Cina',
    emoji: '🍠',
    category: 'staple',
    timeMin: 35,
    difficulty: 1,
    minMonth: 12,
    allergens: [],
    ingredients: [
      { key: 'millet', qty: 1 },
      { key: 'yam',    qty: 2 },
    ],
    steps: [
      { emoji: '🌾', textId: 'Cuci {millet} 2 kali dengan air bersih.', textZh: '{millet}用清水洗2遍。' },
      { emoji: '🍠', textId: 'Kupas {yam} (pegang dengan kantong plastik, getahnya bikin gatal). Potong dadu kecil.', textZh: '{yam}去皮（垫个塑料袋，黏液会让手痒），切成小丁。' },
      { emoji: '💧', textId: 'Masukkan millet dan 4 mangkuk air ke panci. Masak api besar sampai mendidih.', textZh: '小米加4碗水，大火煮开。' },
      { emoji: '🔥', textId: 'Kecilkan api. Masukkan ubi cina. Masak 25 menit, aduk setiap 5 menit.', textZh: '转小火放山药，煮25分钟，每5分钟搅一下。' },
      { emoji: '🥄', textId: 'Tekan ubi cina dengan sendok sampai hancur.', textZh: '用勺子把山药压碎。' },
      { emoji: '🍽️', textId: 'Matikan api. Tunggu sampai hangat, baru berikan ke bayi.', textZh: '关火，晾到温热再给宝宝吃。' },
    ],
    tipId: 'Getah ubi cina bikin tangan gatal — selalu pegang dengan kantong plastik.',
    tipZh: '山药黏液会让手发痒，削皮时垫着塑料袋。',
  },
  {
    id: 'banana-oats',
    nameZh: '香蕉燕麦糊',
    nameId: 'Oat Pisang',
    emoji: '🍌',
    category: 'staple',
    timeMin: 10,
    difficulty: 1,
    minMonth: 12,
    allergens: [],
    ingredients: [
      { key: 'oats',   qty: 1 },
      { key: 'banana', qty: 1 },
    ],
    steps: [
      { emoji: '🥣', textId: 'Masukkan {oats} dan 1 mangkuk air ke panci kecil.', textZh: '{oats}加1碗水放进小锅。' },
      { emoji: '🔥', textId: 'Masak 3 menit dengan api kecil sampai kental. Aduk terus.', textZh: '小火煮3分钟，边煮边搅，煮到粘稠。' },
      { emoji: '🍌', textId: 'Kupas {banana}. Haluskan dengan garpu di mangkuk.', textZh: '{banana}剥皮，用叉子压成泥。' },
      { emoji: '🥄', textId: 'Masukkan pisang ke oat. Aduk rata.', textZh: '香蕉泥拌进燕麦糊里，搅匀。' },
      { emoji: '🍽️', textId: 'Tunggu sampai hangat, baru berikan ke bayi.', textZh: '晾到温热再给宝宝吃。' },
    ],
    tipId: 'Tidak perlu gula — pisang sudah manis.',
    tipZh: '不用加糖，香蕉本身够甜。',
  },
  {
    id: 'corn-pakcoy-congee',
    nameZh: '玉米小白菜粥',
    nameId: 'Bubur Jagung Pakcoy',
    emoji: '🌽',
    category: 'staple',
    timeMin: 40,
    difficulty: 1,
    minMonth: 12,
    allergens: [],
    ingredients: [
      { key: 'rice',   qty: 1 },
      { key: 'corn',   qty: 1 },
      { key: 'pakcoy', qty: 1 },
    ],
    steps: [
      { emoji: '🍚', textId: 'Cuci {rice}. Masak dengan 5 mangkuk air selama 25 menit.', textZh: '{rice}洗净，加5碗水煮25分钟。' },
      { emoji: '🌽', textId: 'Serut biji jagung dari {corn} dengan pisau.', textZh: '用刀把{corn}的玉米粒削下来。' },
      { emoji: '🥄', textId: 'Tumbuk jagung sedikit dengan sendok (jagung utuh bisa bikin bayi tersedak).', textZh: '玉米粒用勺子压碎（整粒玉米可能噎到宝宝）。' },
      { emoji: '🔥', textId: 'Masukkan jagung ke bubur. Masak 10 menit.', textZh: '玉米碎放进粥里，煮10分钟。' },
      { emoji: '🥬', textId: 'Cuci {pakcoy}, potong halus. Masukkan ke bubur. Masak 2 menit.', textZh: '{pakcoy}洗净切碎，放粥里煮2分钟。' },
      { emoji: '🍽️', textId: 'Matikan api. Tunggu sampai hangat, baru berikan ke bayi.', textZh: '关火，晾到温热再给宝宝吃。' },
    ],
    tipId: 'Jagung utuh berbahaya untuk bayi — harus ditumbuk dulu.',
    tipZh: '整粒玉米有噎食风险，必须先压碎。',
  },
  {
    id: 'steamed-cod',
    nameZh: '清蒸鳕鱼',
    nameId: 'Ikan Kod Kukus',
    emoji: '🐟',
    category: 'fish',
    timeMin: 15,
    difficulty: 1,
    minMonth: 12,
    allergens: ['fish'],
    ingredients: [
      { key: 'cod',      qty: 2 },
      { key: 'ginger',   qty: 1 },
      { key: 'scallion', qty: 1 },
    ],
    steps: [
      { emoji: '🐟', textId: 'Cuci {cod}. Raba dengan tangan, cabut semua tulang. Periksa 2 kali!', textZh: '{cod}洗净，用手仔细摸，拔掉所有鱼刺。检查2遍！' },
      { emoji: '🫚', textId: 'Iris {ginger}. Taruh di atas ikan.', textZh: '{ginger}切片，铺在鱼上。' },
      { emoji: '💧', textId: 'Rebus air di panci kukusan sampai mendidih.', textZh: '蒸锅里的水烧开。' },
      { emoji: '🔥', textId: 'Kukus ikan 8 menit dengan api besar.', textZh: '鱼放进蒸锅，大火蒸8分钟。' },
      { emoji: '🍴', textId: 'Tes dengan garpu: ikan mudah hancur = sudah matang.', textZh: '用叉子试一下：能轻松压碎就是熟了。' },
      { emoji: '🍋', textId: 'Buang jahe. Boleh peras sedikit jeruk nipis di atas ikan.', textZh: '扔掉姜片，可以挤几滴柠檬汁去腥。' },
      { emoji: '🍽️', textId: 'Hancurkan ikan dengan garpu. Periksa tulang sekali lagi. Tunggu sampai hangat.', textZh: '用叉子把鱼肉压碎，再检查一遍鱼刺，晾到温热。' },
    ],
    tipId: 'Bayi di bawah 1 tahun tidak perlu garam. Di atas 1 tahun boleh sedikit saja.',
    tipZh: '1岁内不加盐，1岁后可以加一点点。',
  },
  {
    id: 'salmon-potato-mash',
    nameZh: '三文鱼土豆泥',
    nameId: 'Salmon Kentang Tumbuk',
    emoji: '🥔',
    category: 'fish',
    timeMin: 25,
    difficulty: 1,
    minMonth: 12,
    allergens: ['fish'],
    ingredients: [
      { key: 'salmon', qty: 1 },
      { key: 'potato', qty: 1 },
    ],
    steps: [
      { emoji: '🥔', textId: 'Kupas {potato}, potong dadu. Rebus 15 menit sampai lembek.', textZh: '{potato}去皮切块，煮15分钟至软烂。' },
      { emoji: '🐟', textId: 'Raba {salmon}, cabut semua tulang. Periksa 2 kali!', textZh: '仔细摸{salmon}，拔掉所有鱼刺。检查2遍！' },
      { emoji: '🔥', textId: 'Kukus ikan 8 menit sampai warnanya pink pucat (matang penuh).', textZh: '鱼蒸8分钟，颜色变成浅粉色就是全熟了。' },
      { emoji: '🥄', textId: 'Hancurkan kentang dengan garpu. Tambah sedikit air hangat supaya lembut.', textZh: '土豆用叉子压成泥，加点温水调软。' },
      { emoji: '🐟', textId: 'Hancurkan ikan, campur ke kentang. Periksa tulang sekali lagi.', textZh: '鱼肉压碎拌进土豆泥，再检查一遍鱼刺。' },
      { emoji: '🍽️', textId: 'Tunggu sampai hangat, baru berikan ke bayi.', textZh: '晾到温热再给宝宝吃。' },
    ],
    tipId: 'Salmon harus matang penuh — tidak boleh setengah matang untuk bayi.',
    tipZh: '给宝宝的三文鱼必须全熟，不能吃半生的。',
  },
  {
    id: 'blanched-shrimp',
    nameZh: '白灼虾（切小段）',
    nameId: 'Udang Rebus (Potong Kecil)',
    emoji: '🦐',
    category: 'shrimp',
    timeMin: 15,
    difficulty: 1,
    minMonth: 18,
    allergens: ['shrimp'],
    ingredients: [
      { key: 'shrimp', qty: 3 },
      { key: 'ginger', qty: 1 },
    ],
    steps: [
      { emoji: '🦐', textId: 'Buang kepala dan kulit {shrimp}. Tarik garis hitam di punggung, buang.', textZh: '{shrimp}去头去壳，挑掉背上的黑线。' },
      { emoji: '💧', textId: 'Rebus air dengan {ginger} sampai mendidih.', textZh: '水加{ginger}烧开。' },
      { emoji: '🔥', textId: 'Masukkan udang. Rebus 3 menit sampai berwarna merah.', textZh: '下虾煮3分钟，变红就是熟了。' },
      { emoji: '💧', textId: 'Angkat udang, masukkan ke air dingin sebentar.', textZh: '捞出过一下凉水。' },
      { emoji: '🔪', textId: 'Potong tiap udang jadi 3 bagian kecil.', textZh: '每只虾切成3小段。' },
      { emoji: '⚠️', textId: 'Pertama kali makan udang: beri 1 potong kecil saja. Tunggu 2 hari, lihat ada alergi atau tidak.', textZh: '第一次吃虾只给1小段，观察2天看有没有过敏。' },
    ],
    tipId: 'Udang makanan alergi tinggi. Pertama kali beri sedikit saja, tunggu 2 hari.',
    tipZh: '虾是高致敏食物，首次一定要少量尝试，观察2天。',
  },
  {
    id: 'shrimp-steamed-egg',
    nameZh: '虾仁蒸蛋',
    nameId: 'Telur Kukus Udang',
    emoji: '🍤',
    category: 'egg',
    timeMin: 20,
    difficulty: 1,
    minMonth: 12,
    allergens: ['egg', 'shrimp'],
    ingredients: [
      { key: 'egg',    qty: 1 },
      { key: 'shrimp', qty: 2 },
    ],
    steps: [
      { emoji: '🦐', textId: 'Kupas {shrimp}, buang garis hitam. Potong kecil-kecil.', textZh: '{shrimp}去壳挑黑线，切碎。' },
      { emoji: '🥚', textId: 'Kocok {egg} dengan 1/2 mangkuk air hangat.', textZh: '{egg}加半碗温水打散。' },
      { emoji: '🥣', textId: 'Saring telur dengan saringan supaya halus (boleh dilewati kalau tidak ada).', textZh: '蛋液过筛更细滑（没有筛子可跳过）。' },
      { emoji: '🍽️', textId: 'Tutup mangkuk dengan piring kecil.', textZh: '碗上盖个小盘子。' },
      { emoji: '🔥', textId: 'Kukus 8 menit dengan api sedang.', textZh: '中火蒸8分钟。' },
      { emoji: '🦐', textId: 'Taruh udang di atas telur. Kukus 3 menit lagi.', textZh: '虾碎铺在蛋上，再蒸3分钟。' },
      { emoji: '🍽️', textId: 'Goyang mangkuk: telur tidak cair = matang. Tunggu sampai hangat.', textZh: '轻轻晃碗，蛋液不流动就是熟了。晾到温热。' },
    ],
    tipId: 'Pakai air hangat — telur kukus jadi halus seperti puding.',
    tipZh: '加温水蒸出来像布丁一样嫩。',
  },
  {
    id: 'steamed-egg-custard',
    nameZh: '鸡蛋羹',
    nameId: 'Telur Kukus Lembut',
    emoji: '🥚',
    category: 'egg',
    timeMin: 15,
    difficulty: 1,
    minMonth: 12,
    allergens: ['egg'],
    ingredients: [
      { key: 'egg', qty: 1 },
    ],
    steps: [
      { emoji: '🥚', textId: 'Kocok {egg} dengan 1/2 mangkuk air hangat.', textZh: '{egg}加半碗温水打散。' },
      { emoji: '🥣', textId: 'Saring telur supaya halus (boleh dilewati).', textZh: '过筛更细腻（可跳过）。' },
      { emoji: '🍽️', textId: 'Tutup mangkuk dengan piring kecil.', textZh: '碗上盖个小盘子。' },
      { emoji: '🔥', textId: 'Kukus 10 menit dengan api sedang-kecil.', textZh: '中小火蒸10分钟。' },
      { emoji: '🍽️', textId: 'Goyang mangkuk: tidak cair = matang.', textZh: '晃一下碗，不流动就是熟了。' },
      { emoji: '🍽️', textId: 'Tunggu sampai hangat, baru berikan ke bayi.', textZh: '晾到温热再给宝宝吃。' },
    ],
    tipId: 'Api terlalu besar bikin telur berlubang-lubang.',
    tipZh: '火太大会蒸出蜂窝，要用中小火。',
  },
  {
    id: 'mushroom-chicken',
    nameZh: '香菇鸡肉末',
    nameId: 'Ayam Cincang Jamur',
    emoji: '🍄',
    category: 'chicken',
    timeMin: 20,
    difficulty: 1,
    minMonth: 12,
    allergens: [],
    ingredients: [
      { key: 'chicken',  qty: 1 },
      { key: 'mushroom', qty: 2 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Cincang {chicken} sampai halus.', textZh: '{chicken}剁成肉末。' },
      { emoji: '🍄', textId: 'Cuci {mushroom}, potong kecil-kecil.', textZh: '{mushroom}洗净切碎。' },
      { emoji: '🔥', textId: 'Panaskan 1 sendok teh minyak. Masukkan ayam. Masak 3 menit.', textZh: '热锅放1茶勺油，下鸡肉末炒3分钟。' },
      { emoji: '💧', textId: 'Masukkan jamur dan 1/2 mangkuk air.', textZh: '放香菇，加半碗水。' },
      { emoji: '🔥', textId: 'Tutup panci. Masak 8 menit dengan api kecil sampai jamur benar-benar lembek.', textZh: '盖上锅盖，小火焖8分钟，焖到香菇很软。' },
      { emoji: '🍽️', textId: 'Matikan api. Tunggu sampai hangat, baru berikan ke bayi.', textZh: '关火，晾到温热再给宝宝吃。' },
    ],
    tipId: 'Jamur harus benar-benar lembek supaya bayi bisa mengunyah.',
    tipZh: '香菇要焖到很软，宝宝才嚼得动。',
  },
  {
    id: 'beef-potato-stew',
    nameZh: '土豆炖牛肉末',
    nameId: 'Daging Sapi Cincang Kentang',
    emoji: '🥔',
    category: 'beef',
    timeMin: 25,
    difficulty: 1,
    minMonth: 12,
    allergens: [],
    ingredients: [
      { key: 'beef',   qty: 1 },
      { key: 'potato', qty: 1 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Cincang {beef} sehalus mungkin.', textZh: '{beef}尽量剁细。' },
      { emoji: '🥔', textId: 'Kupas {potato}, potong dadu kecil (1 cm).', textZh: '{potato}去皮，切成1厘米的小丁。' },
      { emoji: '🔥', textId: 'Panaskan 1 sendok teh minyak. Masukkan daging. Masak 3 menit.', textZh: '热锅放1茶勺油，下牛肉末炒3分钟。' },
      { emoji: '💧', textId: 'Masukkan kentang dan 1 mangkuk air.', textZh: '放土豆，加1碗水。' },
      { emoji: '🔥', textId: 'Tutup panci. Masak 15 menit dengan api kecil sampai kentang lembek.', textZh: '盖盖小火焖15分钟，焖到土豆软烂。' },
      { emoji: '🥄', textId: 'Tekan sebagian kentang dengan sendok supaya kuah jadi kental.', textZh: '用勺子压碎部分土豆，汤会变稠。' },
      { emoji: '🍽️', textId: 'Matikan api. Tunggu sampai hangat, baru berikan ke bayi.', textZh: '关火，晾到温热再给宝宝吃。' },
    ],
    tipId: 'Daging sapi lebih lama matang — cincang sehalus mungkin.',
    tipZh: '牛肉不容易烂，剁得越细越好。',
  },
  {
    id: 'pork-liver-spinach-soup',
    nameZh: '菠菜猪肝汤',
    nameId: 'Sup Bayam Hati Babi',
    emoji: '🐷',
    category: 'soup',
    timeMin: 25,
    difficulty: 1,
    minMonth: 12,
    allergens: [],
    ingredients: [
      { key: 'pork_liver', qty: 1 },
      { key: 'spinach',    qty: 1 },
      { key: 'ginger',     qty: 1 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Potong {pork_liver} tipis-tipis. Rendam di air 10 menit. Buang airnya.', textZh: '{pork_liver}切薄片，泡水10分钟去血水，倒掉水。' },
      { emoji: '💧', textId: 'Rebus 2 mangkuk air dengan {ginger}.', textZh: '2碗水加{ginger}烧开。' },
      { emoji: '🔥', textId: 'Masukkan hati. Rebus 3 menit. Buang busa di atas air.', textZh: '下猪肝煮3分钟，撇掉浮沫。' },
      { emoji: '🔪', textId: 'Angkat hati. Potong kecil-kecil.', textZh: '捞出猪肝，切碎。' },
      { emoji: '🥬', textId: 'Masukkan kembali hati dan {spinach} yang sudah dipotong. Rebus 2 menit.', textZh: '猪肝放回锅里，加切好的{spinach}，煮2分钟。' },
      { emoji: '🍽️', textId: 'Buang jahe. Tunggu sampai hangat, baru berikan ke bayi.', textZh: '挑出姜片扔掉，晾到温热再给宝宝吃。' },
    ],
    tipId: 'Hati babi kaya zat besi — bagus untuk bayi. 1 kali seminggu cukup.',
    tipZh: '猪肝补铁，每周吃1次就够了。',
  },
  {
    id: 'winter-melon-meatball-soup',
    nameZh: '冬瓜肉丸汤',
    nameId: 'Sup Bligo Bakso Kecil',
    emoji: '🍈',
    category: 'soup',
    timeMin: 25,
    difficulty: 1,
    minMonth: 12,
    allergens: [],
    ingredients: [
      { key: 'pork',         qty: 1 },
      { key: 'winter_melon', qty: 2 },
      { key: 'ginger',       qty: 1 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Cincang {pork} sangat halus. Tambah 1 sendok teh tepung maizena. Aduk 2 menit.', textZh: '{pork}剁得极细，加1茶勺淀粉，搅2分钟。' },
      { emoji: '🥄', textId: 'Buat bola-bola kecil (1 cm) dengan sendok.', textZh: '用勺子做成1厘米的小丸子。' },
      { emoji: '🍈', textId: 'Kupas {winter_melon}, potong tipis-tipis.', textZh: '{winter_melon}去皮切薄片。' },
      { emoji: '💧', textId: 'Rebus 2 mangkuk air dengan {ginger}. Masukkan bligo. Rebus 5 menit.', textZh: '2碗水加{ginger}烧开，放冬瓜煮5分钟。' },
      { emoji: '🔥', textId: 'Masukkan bola daging satu-satu. Api kecil, rebus 5 menit. Bola mengapung = matang.', textZh: '一个个下小丸子，小火煮5分钟，丸子浮起来就是熟了。' },
      { emoji: '🍽️', textId: 'Buang jahe. Tunggu sampai hangat, baru berikan ke bayi.', textZh: '挑出姜片扔掉，晾到温热再给宝宝吃。' },
    ],
    tipId: 'Bola daging harus kecil (1 cm) supaya bayi tidak tersedak.',
    tipZh: '丸子要做小一点，防止宝宝噎到。',
  },
  {
    id: 'tomato-tofu-soup',
    nameZh: '番茄豆腐汤',
    nameId: 'Sup Tomat Tahu',
    emoji: '🍅',
    category: 'soup',
    timeMin: 15,
    difficulty: 1,
    minMonth: 12,
    allergens: ['soy'],
    ingredients: [
      { key: 'tomato', qty: 1 },
      { key: 'tofu',   qty: 2 },
    ],
    steps: [
      { emoji: '🍅', textId: 'Rebus {tomato} di air panas 1 menit. Kupas kulitnya. Potong kecil-kecil.', textZh: '{tomato}开水烫1分钟，去皮切碎。' },
      { emoji: '🫘', textId: 'Potong {tofu} dadu kecil (1 cm).', textZh: '{tofu}切成1厘米的小丁。' },
      { emoji: '🔥', textId: 'Panaskan 1 sendok teh minyak. Masukkan tomat. Masak 3 menit sampai lembek.', textZh: '热锅放1茶勺油，下番茄炒3分钟至软烂。' },
      { emoji: '💧', textId: 'Tambah 2 mangkuk air. Masak sampai mendidih.', textZh: '加2碗水煮开。' },
      { emoji: '🫘', textId: 'Masukkan tahu. Rebus 3 menit.', textZh: '放豆腐煮3分钟。' },
      { emoji: '🍽️', textId: 'Matikan api. Tunggu sampai hangat, baru berikan ke bayi.', textZh: '关火，晾到温热再给宝宝吃。' },
    ],
    tipId: 'Tahu lembut, tidak perlu dikunyah — cocok untuk bayi yang baru belajar makan.',
    tipZh: '豆腐软嫩不用嚼，适合刚学吃饭的宝宝。',
  },
  {
    id: 'laver-egg-soup',
    nameZh: '紫菜蛋花汤',
    nameId: 'Sup Telur Rumput Laut',
    emoji: '🍲',
    category: 'soup',
    timeMin: 10,
    difficulty: 1,
    minMonth: 12,
    allergens: ['egg'],
    ingredients: [
      { key: 'laver', qty: 1 },
      { key: 'egg',   qty: 1 },
    ],
    steps: [
      { emoji: '🌊', textId: 'Sobek {laver} kecil-kecil ke dalam mangkuk.', textZh: '{laver}撕成小块放碗里。' },
      { emoji: '🥚', textId: 'Kocok {egg} dengan garpu.', textZh: '{egg}用叉子打散。' },
      { emoji: '💧', textId: 'Rebus 2 mangkuk air sampai mendidih.', textZh: '2碗水烧开。' },
      { emoji: '🌊', textId: 'Masukkan rumput laut. Rebus 1 menit.', textZh: '放紫菜煮1分钟。' },
      { emoji: '🥚', textId: 'Tuang telur pelan-pelan sambil diaduk, jadi bunga telur. Matikan api.', textZh: '慢慢倒入蛋液，边倒边搅成蛋花，关火。' },
      { emoji: '🍽️', textId: 'Tunggu sampai hangat, baru berikan ke bayi.', textZh: '晾到温热再给宝宝吃。' },
    ],
    tipId: 'Rumput laut sudah ada rasa — tidak perlu banyak garam.',
    tipZh: '紫菜自带鲜味，盐要少放。',
  },
  {
    id: 'steamed-broccoli',
    nameZh: '清蒸西兰花',
    nameId: 'Brokoli Kukus',
    emoji: '🥦',
    category: 'veg',
    timeMin: 15,
    difficulty: 1,
    minMonth: 12,
    allergens: [],
    ingredients: [
      { key: 'broccoli', qty: 1 },
    ],
    steps: [
      { emoji: '🥦', textId: 'Potong {broccoli} jadi kuntum-kuntum kecil.', textZh: '{broccoli}切成小朵。' },
      { emoji: '💧', textId: 'Rendam di air garam 5 menit. Cuci dengan air bersih.', textZh: '淡盐水泡5分钟，再用清水洗净。' },
      { emoji: '🔥', textId: 'Kukus 8 menit. Tes dengan garpu: garpu mudah masuk = matang.', textZh: '蒸8分钟，叉子能轻松穿透就是熟了。' },
      { emoji: '🍽️', textId: 'Untuk finger food: biarkan tangkainya panjang supaya bayi bisa pegang sendiri.', textZh: '做手指食物的话留长一点的柄，方便宝宝自己抓。' },
      { emoji: '🍽️', textId: 'Tunggu sampai hangat, baru berikan ke bayi.', textZh: '晾到温热再给宝宝吃。' },
    ],
    tipId: 'Brokoli kukus = finger food yang bagus, bayi belajar makan sendiri.',
    tipZh: '蒸西兰花是很好的手指食物，让宝宝练习自己抓着吃。',
  },
  {
    id: 'steamed-pumpkin',
    nameZh: '蒸南瓜',
    nameId: 'Labu Kukus',
    emoji: '🎃',
    category: 'veg',
    timeMin: 20,
    difficulty: 1,
    minMonth: 12,
    allergens: [],
    ingredients: [
      { key: 'pumpkin', qty: 3 },
    ],
    steps: [
      { emoji: '🎃', textId: 'Kupas {pumpkin}, potong dadu (2 cm).', textZh: '{pumpkin}去皮，切成2厘米的块。' },
      { emoji: '🔥', textId: 'Kukus 15 menit sampai lembek.', textZh: '蒸15分钟至软烂。' },
      { emoji: '🥄', textId: 'Bayi kecil: hancurkan dengan garpu jadi puree. Bayi lebih besar: biarkan utuh sebagai finger food.', textZh: '小月龄宝宝用叉子压成泥；大宝宝可以直接当手指食物。' },
      { emoji: '🍽️', textId: 'Tunggu sampai hangat, baru berikan ke bayi.', textZh: '晾到温热再给宝宝吃。' },
    ],
    tipId: 'Labu manis alami — bayi biasanya suka.',
    tipZh: '南瓜自带甜味，宝宝一般都爱吃。',
  },
  {
    id: 'carrot-sticks',
    nameZh: '蒸胡萝卜条',
    nameId: 'Stik Wortel Kukus',
    emoji: '🥕',
    category: 'veg',
    timeMin: 20,
    difficulty: 1,
    minMonth: 12,
    allergens: [],
    ingredients: [
      { key: 'carrot', qty: 1 },
    ],
    steps: [
      { emoji: '🥕', textId: 'Kupas {carrot}.', textZh: '{carrot}去皮。' },
      { emoji: '🔪', textId: 'Potong jadi stik panjang, sebesar jari.', textZh: '切成手指粗的长条。' },
      { emoji: '🔥', textId: 'Kukus 12 menit sampai lembek. Tes dengan garpu — harus mudah masuk.', textZh: '蒸12分钟至软，用叉子试，能轻松穿透才行。' },
      { emoji: '🍽️', textId: 'Taruh di piring. Biarkan bayi pegang dan makan sendiri.', textZh: '放盘子里，让宝宝自己抓着吃。' },
    ],
    tipId: 'Finger food melatih bayi makan sendiri. Wortel harus lembek, tidak boleh keras!',
    tipZh: '手指食物锻炼宝宝自主进食，胡萝卜必须蒸软，不能硬！',
  },
  {
    id: 'pakcoy-tofu-mash',
    nameZh: '小白菜豆腐泥',
    nameId: 'Pakcoy Tahu Tumbuk',
    emoji: '🥬',
    category: 'veg',
    timeMin: 10,
    difficulty: 1,
    minMonth: 12,
    allergens: ['soy'],
    ingredients: [
      { key: 'pakcoy', qty: 1 },
      { key: 'tofu',   qty: 1 },
    ],
    steps: [
      { emoji: '🥬', textId: 'Cuci {pakcoy}. Rebus 2 menit. Potong halus.', textZh: '{pakcoy}洗净，煮2分钟，切碎。' },
      { emoji: '🫘', textId: 'Rebus {tofu} 2 menit.', textZh: '{tofu}煮2分钟。' },
      { emoji: '🥄', textId: 'Hancurkan tahu dengan garpu.', textZh: '豆腐用叉子压碎。' },
      { emoji: '🥣', textId: 'Campur sayur dan tahu. Aduk rata.', textZh: '菜碎和豆腐拌在一起，搅匀。' },
      { emoji: '🍽️', textId: 'Tunggu sampai hangat, baru berikan ke bayi.', textZh: '晾到温热再给宝宝吃。' },
    ],
    tipId: 'Sayur hijau + protein dalam satu mangkuk.',
    tipZh: '一碗里蔬菜和蛋白质都有了。',
  },
  {
    id: 'zucchini-egg-mash',
    nameZh: '西葫芦蛋黄泥',
    nameId: 'Zukini Kuning Telur Tumbuk',
    emoji: '🥒',
    category: 'veg',
    timeMin: 20,
    difficulty: 1,
    minMonth: 12,
    allergens: ['egg'],
    ingredients: [
      { key: 'zucchini', qty: 1 },
      { key: 'egg',      qty: 1 },
    ],
    steps: [
      { emoji: '🥚', textId: 'Rebus {egg} 10 menit. Ambil kuning telurnya saja.', textZh: '{egg}煮10分钟，只取蛋黄。' },
      { emoji: '🥒', textId: 'Kupas {zucchini}, potong tipis-tipis.', textZh: '{zucchini}去皮切薄片。' },
      { emoji: '🔥', textId: 'Kukus zukini 8 menit sampai lembek.', textZh: '西葫芦蒸8分钟至软。' },
      { emoji: '🥄', textId: 'Hancurkan zukini dan kuning telur dengan garpu. Tambah sedikit air hangat.', textZh: '西葫芦和蛋黄一起压成泥，加点温水调稀。' },
      { emoji: '🍽️', textId: 'Tunggu sampai hangat, baru berikan ke bayi.', textZh: '晾到温热再给宝宝吃。' },
    ],
    tipId: 'Kuning telur kaya zat besi. Kalau bayi sudah biasa makan telur utuh, boleh pakai putihnya juga.',
    tipZh: '蛋黄补铁。宝宝已经排敏全蛋的话，可以用整蛋。',
  },
  {
    id: 'steamed-salmon',
    nameZh: '清蒸三文鱼',
    nameId: 'Salmon Kukus',
    emoji: '🐟',
    category: 'fish',
    timeMin: 15,
    difficulty: 1,
    minMonth: 12,
    allergens: ['fish'],
    ingredients: [
      { key: 'salmon',   qty: 2 },
      { key: 'ginger',   qty: 1 },
      { key: 'scallion', qty: 1 },
    ],
    steps: [
      { emoji: '🐟', textId: 'Cuci {salmon}. Raba dengan tangan, cabut semua tulang. Periksa 2 kali!', textZh: '{salmon}洗净，用手仔细摸，拔掉所有鱼刺。检查2遍！' },
      { emoji: '🫚', textId: 'Iris {ginger}. Taruh di atas ikan.', textZh: '{ginger}切片，铺在鱼上。' },
      { emoji: '💧', textId: 'Rebus air di panci kukusan sampai mendidih.', textZh: '蒸锅里的水烧开。' },
      { emoji: '🔥', textId: 'Kukus 8 menit dengan api besar, sampai warna ikan pink pucat (matang penuh).', textZh: '大火蒸8分钟，鱼肉变成浅粉色就是全熟了。' },
      { emoji: '🍋', textId: 'Buang jahe. Boleh peras sedikit jeruk nipis di atas ikan.', textZh: '扔掉姜片，可以挤几滴柠檬汁去腥。' },
      { emoji: '🍽️', textId: 'Hancurkan ikan dengan garpu. Periksa tulang sekali lagi. Tunggu sampai hangat.', textZh: '用叉子压碎鱼肉，再检查一遍鱼刺，晾到温热。' },
    ],
    tipId: 'Salmon untuk bayi harus matang penuh, tidak boleh setengah matang.',
    tipZh: '给宝宝的三文鱼必须全熟，不能半生。',
  },
  {
    id: 'salmon-steamed-egg',
    nameZh: '三文鱼蒸蛋',
    nameId: 'Telur Kukus Salmon',
    emoji: '🍳',
    category: 'egg',
    timeMin: 20,
    difficulty: 1,
    minMonth: 12,
    allergens: ['egg', 'fish'],
    ingredients: [
      { key: 'egg',    qty: 1 },
      { key: 'salmon', qty: 1 },
    ],
    steps: [
      { emoji: '🐟', textId: 'Raba {salmon}, cabut semua tulang. Periksa 2 kali! Potong kecil-kecil.', textZh: '仔细摸{salmon}，拔掉所有鱼刺，检查2遍！切成小丁。' },
      { emoji: '🥚', textId: 'Kocok {egg} dengan 1/2 mangkuk air hangat.', textZh: '{egg}加半碗温水打散。' },
      { emoji: '🥣', textId: 'Saring telur supaya halus (boleh dilewati).', textZh: '蛋液过筛更细滑（可跳过）。' },
      { emoji: '🍽️', textId: 'Tutup mangkuk dengan piring kecil. Kukus 8 menit api sedang.', textZh: '碗上盖盘，中火蒸8分钟。' },
      { emoji: '🐟', textId: 'Taruh ikan di atas telur. Kukus 4 menit lagi.', textZh: '鱼丁铺在蛋上，再蒸4分钟。' },
      { emoji: '🍽️', textId: 'Goyang mangkuk: tidak cair = matang. Tunggu sampai hangat.', textZh: '晃碗不流动即熟，晾到温热。' },
    ],
    tipId: 'Ikan harus matang penuh — kukus 4 menit tidak boleh kurang.',
    tipZh: '鱼必须全熟，最后4分钟不能少。',
  },
  {
    id: 'tomato-chicken',
    nameZh: '番茄鸡肉末',
    nameId: 'Ayam Cincang Tomat',
    emoji: '🍅',
    category: 'chicken',
    timeMin: 20,
    difficulty: 1,
    minMonth: 12,
    allergens: [],
    ingredients: [
      { key: 'chicken', qty: 1 },
      { key: 'tomato',  qty: 1 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Cincang {chicken} sampai halus.', textZh: '{chicken}剁成肉末。' },
      { emoji: '🍅', textId: 'Rebus {tomato} di air panas 1 menit. Kupas kulitnya. Potong kecil-kecil.', textZh: '{tomato}开水烫1分钟，去皮切碎。' },
      { emoji: '🔥', textId: 'Panaskan 1 sendok teh minyak. Masukkan ayam. Masak 3 menit.', textZh: '热锅放1茶勺油，下鸡肉末炒3分钟。' },
      { emoji: '🍅', textId: 'Masukkan tomat. Masak 3 menit sampai lembek.', textZh: '下番茄炒3分钟至软烂。' },
      { emoji: '💧', textId: 'Tambah 1/2 mangkuk air. Tutup panci, masak 5 menit api kecil.', textZh: '加半碗水，盖盖小火焖5分钟。' },
      { emoji: '🍽️', textId: 'Matikan api. Tunggu sampai hangat, baru berikan ke bayi.', textZh: '关火，晾到温热再给宝宝吃。' },
    ],
    tipId: 'Kuah tomat enak dicampur ke bubur atau nasi.',
    tipZh: '番茄汁拌粥拌饭都好吃。',
  },
  {
    id: 'chicken-pumpkin-mash',
    nameZh: '鸡肉南瓜泥',
    nameId: 'Ayam Labu Tumbuk',
    emoji: '🎃',
    category: 'chicken',
    timeMin: 25,
    difficulty: 1,
    minMonth: 12,
    allergens: [],
    ingredients: [
      { key: 'chicken', qty: 1 },
      { key: 'pumpkin', qty: 2 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Potong {chicken} kecil-kecil.', textZh: '{chicken}切小块。' },
      { emoji: '🎃', textId: 'Kupas {pumpkin}, potong dadu.', textZh: '{pumpkin}去皮切块。' },
      { emoji: '🔥', textId: 'Kukus ayam dan labu bersama selama 15 menit.', textZh: '鸡肉和南瓜一起蒸15分钟。' },
      { emoji: '🔪', textId: 'Ayam: cincang halus.', textZh: '鸡肉取出剁碎。' },
      { emoji: '🥄', textId: 'Labu: hancurkan dengan garpu. Campur dengan ayam cincang.', textZh: '南瓜压成泥，拌入鸡肉碎。' },
      { emoji: '🍽️', textId: 'Tunggu sampai hangat, baru berikan ke bayi.', textZh: '晾到温热再给宝宝吃。' },
    ],
    tipId: 'Rasa manis labu menutupi rasa daging — bayi yang tidak suka daging biasanya mau.',
    tipZh: '南瓜的甜味能盖住肉味，不爱吃肉的宝宝也能接受。',
  },
  {
    id: 'pork-steamed-egg',
    nameZh: '肉末蒸蛋',
    nameId: 'Telur Kukus Daging Cincang',
    emoji: '🥚',
    category: 'egg',
    timeMin: 20,
    difficulty: 1,
    minMonth: 12,
    allergens: ['egg'],
    ingredients: [
      { key: 'egg',  qty: 1 },
      { key: 'pork', qty: 1 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Cincang {pork} sampai halus.', textZh: '{pork}剁成肉末。' },
      { emoji: '💧', textId: 'Rebus daging cincang di air mendidih 2 menit. Angkat, tiriskan (supaya tidak berbau).', textZh: '肉末开水焯2分钟捞出（去腥去浮沫）。' },
      { emoji: '🥚', textId: 'Kocok {egg} dengan 1/2 mangkuk air hangat.', textZh: '{egg}加半碗温水打散。' },
      { emoji: '🥣', textId: 'Masukkan daging ke telur. Aduk rata.', textZh: '肉末拌进蛋液，搅匀。' },
      { emoji: '🍽️', textId: 'Tutup mangkuk dengan piring. Kukus 10 menit api sedang.', textZh: '盖盘，中火蒸10分钟。' },
      { emoji: '🍽️', textId: 'Goyang mangkuk: tidak cair = matang. Tunggu sampai hangat.', textZh: '晃碗不流动即熟，晾到温热。' },
    ],
    tipId: 'Daging direbus dulu supaya telur kukus bersih, tidak berbusa.',
    tipZh: '肉末先焯水，蒸出来的蛋羹更干净。',
  },
  {
    id: 'beef-carrot-mash',
    nameZh: '牛肉胡萝卜泥',
    nameId: 'Daging Sapi Wortel Tumbuk',
    emoji: '🥕',
    category: 'beef',
    timeMin: 25,
    difficulty: 1,
    minMonth: 12,
    allergens: [],
    ingredients: [
      { key: 'beef',   qty: 1 },
      { key: 'carrot', qty: 1 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Cincang {beef} sehalus mungkin.', textZh: '{beef}尽量剁细。' },
      { emoji: '🥕', textId: 'Kupas {carrot}, potong dadu kecil.', textZh: '{carrot}去皮切小丁。' },
      { emoji: '🔥', textId: 'Panaskan 1 sendok teh minyak. Masukkan daging. Masak 3 menit.', textZh: '热锅放1茶勺油，下牛肉末炒3分钟。' },
      { emoji: '💧', textId: 'Masukkan wortel dan 1 mangkuk air. Tutup panci, masak 15 menit api kecil.', textZh: '放胡萝卜加1碗水，盖盖小火焖15分钟。' },
      { emoji: '🥄', textId: 'Tekan wortel dengan sendok sampai hancur.', textZh: '用勺子把胡萝卜压碎成糊。' },
      { emoji: '🍽️', textId: 'Matikan api. Tunggu sampai hangat, baru berikan ke bayi.', textZh: '关火，晾到温热再给宝宝吃。' },
    ],
    tipId: 'Wortel harus lembek sekali supaya bayi mudah menelan.',
    tipZh: '胡萝卜要焖到很软，宝宝才好咽。',
  },
  {
    id: 'cod-tofu-stew',
    nameZh: '鳕鱼豆腐煲',
    nameId: 'Ikan Kod Tahu Kuah',
    emoji: '🐟',
    category: 'tofu',
    timeMin: 20,
    difficulty: 1,
    minMonth: 12,
    allergens: ['fish', 'soy'],
    ingredients: [
      { key: 'cod',    qty: 1 },
      { key: 'tofu',   qty: 1 },
      { key: 'ginger', qty: 1 },
    ],
    steps: [
      { emoji: '🐟', textId: 'Raba {cod}, cabut semua tulang. Periksa 2 kali! Potong kecil-kecil.', textZh: '仔细摸{cod}，拔掉所有鱼刺，检查2遍！切小块。' },
      { emoji: '🫘', textId: 'Potong {tofu} dadu kecil (1 cm).', textZh: '{tofu}切成1厘米的小丁。' },
      { emoji: '💧', textId: 'Rebus 1 mangkuk air dengan {ginger}.', textZh: '1碗水加{ginger}煮开。' },
      { emoji: '🫘', textId: 'Masukkan tahu. Rebus 3 menit.', textZh: '下豆腐煮3分钟。' },
      { emoji: '🐟', textId: 'Masukkan ikan. Rebus 4 menit. Ambil jahe, buang.', textZh: '下鱼块煮4分钟，挑出姜片扔掉。' },
      { emoji: '🍽️', textId: 'Periksa tulang sekali lagi. Tunggu sampai hangat, baru berikan ke bayi.', textZh: '再检查一遍鱼刺，晾到温热再给宝宝吃。' },
    ],
    tipId: 'Ikan + tahu = protein ganda. Kuah sudah segar, tidak perlu banyak garam.',
    tipZh: '鱼加豆腐双重蛋白，汤自带鲜味，盐要少放。',
  },
  {
    id: 'pork-pakcoy-mash',
    nameZh: '猪肉小白菜泥',
    nameId: 'Daging Babi Pakcoy Tumbuk',
    emoji: '🥬',
    category: 'pork',
    timeMin: 20,
    difficulty: 1,
    minMonth: 12,
    allergens: [],
    ingredients: [
      { key: 'pork',   qty: 1 },
      { key: 'pakcoy', qty: 1 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Cincang {pork} sampai halus.', textZh: '{pork}剁成肉末。' },
      { emoji: '🔥', textId: 'Panaskan 1 sendok teh minyak. Masukkan daging. Masak 3 menit.', textZh: '热锅放1茶勺油，下猪肉末炒3分钟。' },
      { emoji: '💧', textId: 'Tambah 1/2 mangkuk air. Tutup panci, masak 8 menit api kecil.', textZh: '加半碗水，盖盖小火焖8分钟。' },
      { emoji: '🥬', textId: 'Masukkan {pakcoy} yang sudah dipotong halus. Masak 2 menit.', textZh: '放切好的{pakcoy}，煮2分钟。' },
      { emoji: '🥄', textId: 'Tekan campuran dengan sendok sampai lembut.', textZh: '整体用勺子压软。' },
      { emoji: '🍽️', textId: 'Matikan api. Tunggu sampai hangat, baru berikan ke bayi.', textZh: '关火，晾到温热再给宝宝吃。' },
    ],
    tipId: 'Cocok dicampur ke bubur nasi — jadi satu porsi lengkap.',
    tipZh: '拌进大米粥里，就是完整的一餐。',
  },
  {
    id: 'pumpkin-rice-congee',
    nameZh: '南瓜大米粥',
    nameId: 'Bubur Nasi Labu',
    emoji: '🎃',
    category: 'staple',
    timeMin: 40,
    difficulty: 1,
    minMonth: 12,
    allergens: [],
    ingredients: [
      { key: 'rice',    qty: 1 },
      { key: 'pumpkin', qty: 2 },
    ],
    steps: [
      { emoji: '🍚', textId: 'Cuci {rice} 2 kali dengan air bersih.', textZh: '{rice}用清水洗2遍。' },
      { emoji: '🎃', textId: 'Kupas {pumpkin}, potong dadu kecil (1 cm).', textZh: '{pumpkin}去皮，切成1厘米的小丁。' },
      { emoji: '💧', textId: 'Masukkan beras dan 5 mangkuk air ke panci. Masak api besar sampai mendidih.', textZh: '大米加5碗水，大火煮开。' },
      { emoji: '🔥', textId: 'Kecilkan api. Masukkan labu. Masak 30 menit, aduk setiap 5 menit.', textZh: '转小火放南瓜，煮30分钟，每5分钟搅一下。' },
      { emoji: '🥄', textId: 'Tekan labu dengan sendok sampai hancur.', textZh: '用勺子把南瓜压碎。' },
      { emoji: '🍽️', textId: 'Matikan api. Tunggu sampai hangat, baru berikan ke bayi.', textZh: '关火，晾到温热再给宝宝吃。' },
    ],
    tipId: 'Labu bikin bubur manis alami, tidak perlu gula.',
    tipZh: '南瓜让粥自带甜味，不用加糖。',
  },
  {
    id: 'apple-oats',
    nameZh: '苹果燕麦糊',
    nameId: 'Oat Apel',
    emoji: '🍎',
    category: 'staple',
    timeMin: 10,
    difficulty: 1,
    minMonth: 12,
    allergens: [],
    ingredients: [
      { key: 'oats',  qty: 1 },
      { key: 'apple', qty: 1 },
    ],
    steps: [
      { emoji: '🍎', textId: 'Kupas {apple}, buang biji, potong kecil-kecil.', textZh: '{apple}去皮去核，切小丁。' },
      { emoji: '🥣', textId: 'Masukkan {oats}, apel, dan 1 mangkuk air ke panci kecil.', textZh: '{oats}、苹果丁加1碗水放进小锅。' },
      { emoji: '🔥', textId: 'Masak 5 menit api kecil sampai kental dan apel lembek. Aduk terus.', textZh: '小火煮5分钟，边煮边搅，煮到粘稠、苹果软。' },
      { emoji: '🥄', textId: 'Tekan apel dengan sendok sampai hancur.', textZh: '用勺子把苹果压碎。' },
      { emoji: '🍽️', textId: 'Tunggu sampai hangat, baru berikan ke bayi.', textZh: '晾到温热再给宝宝吃。' },
    ],
    tipId: 'Apel matang lebih mudah dicerna daripada apel mentah.',
    tipZh: '熟苹果比生苹果更好消化。',
  },
  {
    id: 'broccoli-cod-congee',
    nameZh: '西兰花鳕鱼粥',
    nameId: 'Bubur Brokoli Ikan Kod',
    emoji: '🥦',
    category: 'staple',
    timeMin: 40,
    difficulty: 1,
    minMonth: 12,
    allergens: ['fish'],
    ingredients: [
      { key: 'rice',     qty: 1 },
      { key: 'cod',      qty: 1 },
      { key: 'broccoli', qty: 1 },
      { key: 'ginger',   qty: 1 },
    ],
    steps: [
      { emoji: '🍚', textId: 'Cuci {rice}. Masak dengan 5 mangkuk air dan {ginger} selama 25 menit.', textZh: '{rice}洗净，加5碗水和{ginger}煮25分钟。' },
      { emoji: '🐟', textId: 'Raba {cod}, cabut semua tulang. Periksa 2 kali! Potong kecil-kecil.', textZh: '仔细摸{cod}，拔掉所有鱼刺，检查2遍！切小丁。' },
      { emoji: '🥦', textId: 'Potong {broccoli} jadi kuntum kecil. Rebus 2 menit. Potong halus.', textZh: '{broccoli}切小朵，煮2分钟，再切碎。' },
      { emoji: '🔥', textId: 'Masukkan ikan ke bubur. Masak 5 menit.', textZh: '鱼丁放进粥里，煮5分钟。' },
      { emoji: '🥦', textId: 'Masukkan brokoli. Masak 2 menit. Ambil jahe, buang.', textZh: '放西兰花煮2分钟，挑出姜片扔掉。' },
      { emoji: '🍽️', textId: 'Periksa tulang sekali lagi. Tunggu sampai hangat, baru berikan ke bayi.', textZh: '再检查一遍鱼刺，晾到温热再给宝宝吃。' },
    ],
    tipId: 'Brokoli direbus terpisah dulu supaya tidak terlalu lembek.',
    tipZh: '西兰花先单独煮，口感刚刚好。',
  },
  {
    id: 'corn-chicken-soup',
    nameZh: '玉米鸡肉汤',
    nameId: 'Sup Jagung Ayam',
    emoji: '🌽',
    category: 'soup',
    timeMin: 30,
    difficulty: 1,
    minMonth: 12,
    allergens: [],
    ingredients: [
      { key: 'chicken', qty: 1 },
      { key: 'corn',    qty: 1 },
      { key: 'ginger',  qty: 1 },
    ],
    steps: [
      { emoji: '🔪', textId: 'Cincang {chicken} sampai halus.', textZh: '{chicken}剁成肉末。' },
      { emoji: '🌽', textId: 'Serut biji jagung dari {corn}. Tumbuk sedikit dengan sendok.', textZh: '削下{corn}的玉米粒，用勺子压碎。' },
      { emoji: '💧', textId: 'Rebus 2 mangkuk air dengan {ginger}.', textZh: '2碗水加{ginger}烧开。' },
      { emoji: '🔥', textId: 'Masukkan ayam. Rebus 5 menit. Buang busa di atas air.', textZh: '下鸡肉末煮5分钟，撇掉浮沫。' },
      { emoji: '🌽', textId: 'Masukkan jagung. Rebus 10 menit dengan api kecil.', textZh: '放玉米碎，小火煮10分钟。' },
      { emoji: '🍽️', textId: 'Buang jahe. Tunggu sampai hangat, baru berikan ke bayi.', textZh: '挑出姜片扔掉，晾到温热再给宝宝吃。' },
    ],
    tipId: 'Jagung harus ditumbuk — biji utuh bisa bikin bayi tersedak.',
    tipZh: '玉米必须压碎，整粒有噎食风险。',
  },
  {
    id: 'tomato-cod-soup',
    nameZh: '番茄鳕鱼汤',
    nameId: 'Sup Tomat Ikan Kod',
    emoji: '🍅',
    category: 'soup',
    timeMin: 20,
    difficulty: 1,
    minMonth: 12,
    allergens: ['fish'],
    ingredients: [
      { key: 'tomato', qty: 1 },
      { key: 'cod',    qty: 1 },
      { key: 'ginger', qty: 1 },
    ],
    steps: [
      { emoji: '🍅', textId: 'Rebus {tomato} di air panas 1 menit. Kupas kulitnya. Potong kecil-kecil.', textZh: '{tomato}开水烫1分钟，去皮切碎。' },
      { emoji: '🐟', textId: 'Raba {cod}, cabut semua tulang. Periksa 2 kali! Potong kecil-kecil.', textZh: '仔细摸{cod}，拔掉所有鱼刺，检查2遍！切小块。' },
      { emoji: '🔥', textId: 'Panaskan 1 sendok teh minyak. Masukkan tomat. Masak 3 menit sampai lembek.', textZh: '热锅放1茶勺油，下番茄炒3分钟至软烂。' },
      { emoji: '💧', textId: 'Tambah 2 mangkuk air dan {ginger}. Masak sampai mendidih.', textZh: '加2碗水和{ginger}，煮开。' },
      { emoji: '🐟', textId: 'Masukkan ikan. Rebus 4 menit. Ambil jahe, buang.', textZh: '下鱼块煮4分钟，挑出姜片扔掉。' },
      { emoji: '🍽️', textId: 'Periksa tulang sekali lagi. Tunggu sampai hangat, baru berikan ke bayi.', textZh: '再检查一遍鱼刺，晾到温热再给宝宝吃。' },
    ],
    tipId: 'Kuah tomat sedikit asam-manis — bayi biasanya suka.',
    tipZh: '番茄汤微微酸甜，宝宝一般都爱喝。',
  },
  {
    id: 'steamed-apple-sticks',
    nameZh: '蒸苹果条',
    nameId: 'Stik Apel Kukus',
    emoji: '🍎',
    category: 'veg',
    timeMin: 15,
    difficulty: 1,
    minMonth: 12,
    allergens: [],
    ingredients: [
      { key: 'apple', qty: 1 },
    ],
    steps: [
      { emoji: '🍎', textId: 'Kupas {apple}, buang biji.', textZh: '{apple}去皮去核。' },
      { emoji: '🔪', textId: 'Potong jadi stik panjang, sebesar jari.', textZh: '切成手指粗的长条。' },
      { emoji: '🔥', textId: 'Kukus 8 menit sampai lembek.', textZh: '蒸8分钟至软。' },
      { emoji: '🍽️', textId: 'Tunggu sampai hangat. Biarkan bayi pegang dan makan sendiri.', textZh: '晾到温热，让宝宝自己抓着吃。' },
    ],
    tipId: 'Apel kukus = finger food manis yang sehat.',
    tipZh: '蒸苹果条是健康的甜味手指食物。',
  },
  {
    id: 'spinach-tofu-mash',
    nameZh: '菠菜豆腐泥',
    nameId: 'Bayam Tahu Tumbuk',
    emoji: '🥬',
    category: 'veg',
    timeMin: 10,
    difficulty: 1,
    minMonth: 12,
    allergens: ['soy'],
    ingredients: [
      { key: 'spinach', qty: 1 },
      { key: 'tofu',    qty: 1 },
    ],
    steps: [
      { emoji: '🥬', textId: 'Cuci {spinach}. Rebus 1 menit. Potong halus.', textZh: '{spinach}洗净，焯1分钟，切碎。' },
      { emoji: '🫘', textId: 'Rebus {tofu} 2 menit.', textZh: '{tofu}煮2分钟。' },
      { emoji: '🥄', textId: 'Hancurkan tahu dengan garpu.', textZh: '豆腐用叉子压碎。' },
      { emoji: '🥣', textId: 'Campur bayam dan tahu. Aduk rata.', textZh: '菠菜碎和豆腐拌匀。' },
      { emoji: '🍽️', textId: 'Tunggu sampai hangat, baru berikan ke bayi.', textZh: '晾到温热再给宝宝吃。' },
    ],
    tipId: 'Bayam mengandung zat besi — pasangan yang bagus untuk tahu.',
    tipZh: '菠菜含铁，和豆腐是好搭档。',
  },
  {
    id: 'sweet-potato-sticks',
    nameZh: '蒸红薯条',
    nameId: 'Stik Ubi Jalar Kukus',
    emoji: '🍠',
    category: 'veg',
    timeMin: 20,
    difficulty: 1,
    minMonth: 12,
    allergens: [],
    ingredients: [
      { key: 'sweet_potato', qty: 1 },
    ],
    steps: [
      { emoji: '🍠', textId: 'Kupas {sweet_potato}.', textZh: '{sweet_potato}去皮。' },
      { emoji: '🔪', textId: 'Potong jadi stik panjang, sebesar jari.', textZh: '切成手指粗的长条。' },
      { emoji: '🔥', textId: 'Kukus 15 menit sampai lembek. Tes dengan garpu.', textZh: '蒸15分钟至软，用叉子能轻松穿透。' },
      { emoji: '🍽️', textId: 'Tunggu sampai hangat. Biarkan bayi pegang dan makan sendiri.', textZh: '晾到温热，让宝宝自己抓着吃。' },
    ],
    tipId: 'Ubi kukus manis dan lembut — finger food favorit bayi.',
    tipZh: '蒸红薯条又甜又软，是宝宝最爱的手指食物之一。',
  },
  {
    id: 'banana-egg-waffle',
    nameZh: '香蕉鸡蛋华夫饼',
    nameId: 'Wafel Pisang Telur',
    emoji: '🧇',
    category: 'staple',
    timeMin: 15,
    difficulty: 1,
    minMonth: 12,
    allergens: ['egg'],
    ingredients: [
      { key: 'banana', qty: 1 },
      { key: 'egg',    qty: 2 },
    ],
    steps: [
      { emoji: '🍌', textId: 'Kupas {banana}. Haluskan dengan garpu di mangkuk.', textZh: '{banana}剥皮，用叉子压成泥。' },
      { emoji: '🥚', textId: 'Masukkan {egg}. Kocok sampai rata.', textZh: '打入{egg}，搅拌均匀。' },
      { emoji: '🔥', textId: 'Panaskan cetakan wafel. Olesi sedikit minyak dengan sikat.', textZh: '华夫饼锅预热，用刷子刷一层薄油。' },
      { emoji: '🧇', textId: 'Tuang adonan 2 sendok makan untuk tiap wafel.', textZh: '每格倒2饭勺面糊。' },
      { emoji: '⏲️', textId: 'Tutup cetakan. Masak 4 menit sampai keemasan.', textZh: '盖上盖子，烤4分钟至金黄。' },
      { emoji: '🍽️', textId: 'Angkat. Potong kecil-kecil. Tunggu sampai hangat, baru berikan ke bayi.', textZh: '取出切小块，晾到温热再给宝宝吃。' },
    ],
    tipId: 'Jangan buka cetakan sebelum 3 menit — wafel bisa sobek.',
    tipZh: '前3分钟不要开盖，饼容易破。',
  },
  {
    id: 'oat-banana-waffle',
    nameZh: '燕麦香蕉华夫饼',
    nameId: 'Wafel Oat Pisang',
    emoji: '🧇',
    category: 'staple',
    timeMin: 20,
    difficulty: 1,
    minMonth: 12,
    allergens: ['egg'],
    ingredients: [
      { key: 'oats',   qty: 1 },
      { key: 'banana', qty: 1 },
      { key: 'egg',    qty: 1 },
    ],
    steps: [
      { emoji: '🥣', textId: 'Tumbuk atau blender {oats} sampai jadi bubuk.', textZh: '{oats}用料理机打成粉（或尽量捣碎）。' },
      { emoji: '🍌', textId: 'Haluskan {banana} dengan garpu.', textZh: '{banana}用叉子压成泥。' },
      { emoji: '🥚', textId: 'Campur bubuk oat, pisang, dan {egg}. Aduk jadi adonan kental.', textZh: '燕麦粉、香蕉泥、{egg}混在一起，搅成稠糊。' },
      { emoji: '🔥', textId: 'Panaskan cetakan wafel. Olesi sedikit minyak.', textZh: '华夫饼锅预热，刷一层薄油。' },
      { emoji: '🧇', textId: 'Tuang adonan. Tutup. Masak 4-5 menit sampai keemasan.', textZh: '倒入面糊，盖盖烤4~5分钟至金黄。' },
      { emoji: '🍽️', textId: 'Angkat. Potong kecil-kecil. Tunggu sampai hangat, baru berikan ke bayi.', textZh: '取出切小块，晾到温热再给宝宝吃。' },
    ],
    tipId: 'Adonan harus kental. Kalau terlalu encer, tambah sedikit bubuk oat.',
    tipZh: '面糊要稠一点，太稀就加点燕麦粉。',
  },
  {
    id: 'pumpkin-waffle',
    nameZh: '南瓜华夫饼',
    nameId: 'Wafel Labu',
    emoji: '🎃',
    category: 'staple',
    timeMin: 25,
    difficulty: 1,
    minMonth: 12,
    allergens: ['egg', 'wheat'],
    ingredients: [
      { key: 'pumpkin', qty: 2 },
      { key: 'egg',     qty: 1 },
      { key: 'flour',   qty: 1 },
    ],
    steps: [
      { emoji: '🎃', textId: 'Kupas {pumpkin}, potong dadu. Kukus 10 menit sampai lembek. Haluskan dengan garpu.', textZh: '{pumpkin}去皮切块，蒸10分钟至软，压成泥。' },
      { emoji: '🥚', textId: 'Masukkan {egg}. Aduk rata.', textZh: '加入{egg}，搅匀。' },
      { emoji: '🌾', textId: 'Masukkan {flour} sedikit-sedikit sambil diaduk, sampai jadi adonan kental.', textZh: '分次加入{flour}，搅成稠糊。' },
      { emoji: '🔥', textId: 'Panaskan cetakan wafel. Olesi sedikit minyak.', textZh: '华夫饼锅预热，刷一层薄油。' },
      { emoji: '🧇', textId: 'Tuang adonan. Tutup. Masak 4 menit sampai keemasan.', textZh: '倒入面糊，盖盖烤4分钟至金黄。' },
      { emoji: '🍽️', textId: 'Angkat. Potong kecil-kecil. Tunggu sampai hangat, baru berikan ke bayi.', textZh: '取出切小块，晾到温热再给宝宝吃。' },
    ],
    tipId: 'Labu sudah manis — tidak perlu tambah gula.',
    tipZh: '南瓜够甜，不用加糖。',
  },
  {
    id: 'sweet-potato-waffle',
    nameZh: '红薯华夫饼',
    nameId: 'Wafel Ubi Jalar',
    emoji: '🍠',
    category: 'staple',
    timeMin: 25,
    difficulty: 1,
    minMonth: 12,
    allergens: ['egg', 'wheat'],
    ingredients: [
      { key: 'sweet_potato', qty: 1 },
      { key: 'egg',          qty: 1 },
      { key: 'flour',        qty: 1 },
    ],
    steps: [
      { emoji: '🍠', textId: 'Kupas {sweet_potato}, potong dadu. Kukus 15 menit sampai lembek. Haluskan dengan garpu.', textZh: '{sweet_potato}去皮切块，蒸15分钟至软，压成泥。' },
      { emoji: '🥚', textId: 'Masukkan {egg}. Aduk rata.', textZh: '加入{egg}，搅匀。' },
      { emoji: '🌾', textId: 'Masukkan {flour}. Aduk jadi adonan kental.', textZh: '加入{flour}，搅成稠糊。' },
      { emoji: '🔥', textId: 'Panaskan cetakan wafel. Olesi sedikit minyak.', textZh: '华夫饼锅预热，刷一层薄油。' },
      { emoji: '🧇', textId: 'Tuang adonan. Tutup. Masak 4-5 menit sampai keemasan.', textZh: '倒入面糊，盖盖烤4~5分钟至金黄。' },
      { emoji: '🍽️', textId: 'Angkat. Potong kecil-kecil. Tunggu sampai hangat, baru berikan ke bayi.', textZh: '取出切小块，晾到温热再给宝宝吃。' },
    ],
    tipId: 'Wafel ubi: garing di luar, lembut di dalam.',
    tipZh: '红薯华夫饼外脆里软。',
  },
  {
    id: 'tomato-chicken-farfalle',
    nameZh: '番茄鸡肉蝴蝶面',
    nameId: 'Pasta Kupu-kupu Tomat Ayam',
    emoji: '🦋',
    category: 'staple',
    timeMin: 25,
    difficulty: 1,
    minMonth: 12,
    allergens: ['wheat'],
    ingredients: [
      { key: 'farfalle', qty: 15 },
      { key: 'chicken',  qty: 1 },
      { key: 'tomato',   qty: 1 },
    ],
    steps: [
      { emoji: '💧', textId: 'Rebus {farfalle} di air mendidih 12 menit. Pasta untuk bayi harus lebih lembek dari biasanya.', textZh: '{farfalle}开水下锅煮12分钟，给宝宝吃要比平常煮得更软。' },
      { emoji: '🔪', textId: 'Sambil menunggu: cincang {chicken} sampai halus.', textZh: '等面的时候：把{chicken}剁成肉末。' },
      { emoji: '🍅', textId: 'Rebus {tomato} di air panas 1 menit. Kupas kulitnya. Potong kecil-kecil.', textZh: '{tomato}开水烫1分钟，去皮切碎。' },
      { emoji: '🔥', textId: 'Panaskan 1 sendok teh minyak. Masukkan ayam. Masak 3 menit.', textZh: '热锅放1茶勺油，下鸡肉末炒3分钟。' },
      { emoji: '🍅', textId: 'Masukkan tomat. Masak 3 menit sampai lembek. Tambah 1/2 mangkuk air, masak 2 menit.', textZh: '下番茄炒3分钟至软烂，加半碗水再煮2分钟。' },
      { emoji: '🦋', textId: 'Tiriskan pasta. Masukkan ke saus tomat. Aduk rata 1 menit.', textZh: '蝴蝶面捞出，拌进番茄酱汁里，搅1分钟。' },
      { emoji: '🍽️', textId: 'Matikan api. Tunggu sampai hangat, baru berikan ke bayi.', textZh: '关火，晾到温热再给宝宝吃。' },
    ],
    tipId: 'Pasta kupu-kupu ukurannya pas untuk bayi belajar makan sendiri.',
    tipZh: '蝴蝶面大小适合宝宝练习自己用叉子或手抓着吃。',
  },
  {
    id: 'broccoli-cod-farfalle',
    nameZh: '西兰花鳕鱼蝴蝶面',
    nameId: 'Pasta Kupu-kupu Brokoli Ikan Kod',
    emoji: '🦋',
    category: 'staple',
    timeMin: 25,
    difficulty: 1,
    minMonth: 12,
    allergens: ['fish', 'wheat'],
    ingredients: [
      { key: 'farfalle', qty: 15 },
      { key: 'cod',      qty: 1 },
      { key: 'broccoli', qty: 1 },
      { key: 'ginger',   qty: 1 },
    ],
    steps: [
      { emoji: '💧', textId: 'Rebus {farfalle} di air mendidih 12 menit sampai lembek.', textZh: '{farfalle}开水下锅煮12分钟至软。' },
      { emoji: '🐟', textId: 'Raba {cod}, cabut semua tulang. Periksa 2 kali! Potong kecil-kecil.', textZh: '仔细摸{cod}，拔掉所有鱼刺，检查2遍！切小丁。' },
      { emoji: '🥦', textId: 'Potong {broccoli} jadi kuntum kecil. Rebus 2 menit. Potong halus.', textZh: '{broccoli}切小朵煮2分钟，切碎。' },
      { emoji: '🔥', textId: 'Panaskan 1 sendok teh minyak. Masukkan ikan dan {ginger}. Masak 2 menit.', textZh: '热锅放1茶勺油，下鱼丁和{ginger}炒2分钟。' },
      { emoji: '🥦', textId: 'Masukkan brokoli dan pasta. Tambah 3 sendok makan air. Aduk 2 menit.', textZh: '放西兰花和蝴蝶面，加3饭勺水，翻拌2分钟。' },
      { emoji: '🍽️', textId: 'Ambil jahe, buang. Periksa tulang sekali lagi. Tunggu sampai hangat.', textZh: '挑出姜片扔掉，再检查一遍鱼刺，晾到温热。' },
    ],
    tipId: 'Sedikit air rebusan pasta bisa dipakai supaya saus lebih lengket.',
    tipZh: '可以留两勺煮面水拌进去，酱汁更挂面。',
  },
  {
    id: 'pumpkin-farfalle',
    nameZh: '南瓜蝴蝶面',
    nameId: 'Pasta Kupu-kupu Labu',
    emoji: '🎃',
    category: 'staple',
    timeMin: 25,
    difficulty: 1,
    minMonth: 12,
    allergens: ['wheat'],
    ingredients: [
      { key: 'farfalle', qty: 15 },
      { key: 'pumpkin',  qty: 2 },
    ],
    steps: [
      { emoji: '🎃', textId: 'Kupas {pumpkin}, potong dadu. Kukus 10 menit sampai lembek.', textZh: '{pumpkin}去皮切块，蒸10分钟至软。' },
      { emoji: '🥄', textId: 'Haluskan labu dengan garpu. Tambah sedikit air hangat supaya jadi saus.', textZh: '南瓜压成泥，加点温水调成酱汁状。' },
      { emoji: '💧', textId: 'Rebus {farfalle} di air mendidih 12 menit sampai lembek.', textZh: '{farfalle}开水下锅煮12分钟至软。' },
      { emoji: '🦋', textId: 'Tiriskan pasta. Campur dengan saus labu. Aduk rata.', textZh: '蝴蝶面捞出，拌进南瓜酱里搅匀。' },
      { emoji: '🍽️', textId: 'Tunggu sampai hangat, baru berikan ke bayi.', textZh: '晾到温热再给宝宝吃。' },
    ],
    tipId: 'Saus labu manis alami — tidak perlu garam dan gula.',
    tipZh: '南瓜酱自带甜味，不用放盐和糖。',
  },
];

/* ---------- 中文食材名 → 印尼语词典（用户手动添加食材时用） ---------- */
const ZH_TO_ID = {
  '黄瓜':   { nameId: 'timun',        unitId: 'buah',    emoji: '🥒' },
  '茄子':   { nameId: 'terong',       unitId: 'buah',    emoji: '🍆' },
  '芹菜':   { nameId: 'seledri',      unitId: 'batang',  emoji: '🌿' },
  '白菜':   { nameId: 'sawi putih',   unitId: 'buah',    emoji: '🥬' },
  '生菜':   { nameId: 'selada',       unitId: 'buah',    emoji: '🥬' },
  '豆芽':   { nameId: 'tauge',        unitId: 'genggam', emoji: '🌱' },
  '木耳':   { nameId: 'jamur kuping', unitId: 'genggam', emoji: '🍄' },
  '红枣':   { nameId: 'kurma merah',  unitId: 'butir',   emoji: '🫘' },
  '银耳':   { nameId: 'jamur salju',  unitId: 'genggam', emoji: '🍄' },
  '奶酪':   { nameId: 'keju',         unitId: 'potong',  emoji: '🧀' },
  '酸奶':   { nameId: 'yogurt',       unitId: 'mangkuk', emoji: '🥛' },
  '蓝莓':   { nameId: 'bluberi',      unitId: 'mangkuk', emoji: '🫐' },
  '火龙果': { nameId: 'buah naga',    unitId: 'buah',    emoji: '🐉' },
  '猕猴桃': { nameId: 'kiwi',         unitId: 'buah',    emoji: '🥝' },
  '橙子':   { nameId: 'jeruk',        unitId: 'buah',    emoji: '🍊' },
  '梨':     { nameId: 'pir',          unitId: 'buah',    emoji: '🍐' },
  '草莓':   { nameId: 'stroberi',     unitId: 'butir',   emoji: '🍓' },
  '葡萄':   { nameId: 'anggur',       unitId: 'butir',   emoji: '🍇' },
  '馄饨':   { nameId: 'pangsit',      unitId: 'buah',    emoji: '🥟' },
  '龙须面': { nameId: 'mie halus',    unitId: 'keping',  emoji: '🍜' },
};

/* ---------- 中文别名 → 预设 key ---------- */
const ZH_ALIAS = {
  '马铃薯': 'potato',
  '地瓜':   'sweet_potato',
  '番薯':   'sweet_potato',
};

/* 中文名 → 预设 key（先匹配预设正式名，再匹配别名），没有则 null */
function presetKeyForZh(zh) {
  const p = INGREDIENT_PRESETS.find(x => x.nameZh === zh);
  if (p) return p.key;
  return ZH_ALIAS[zh] || null;
}

/* 自定义食材的图标：能对上预设/词典就用专属图标，否则默认 📦 */
function customEmoji(zh) {
  if (!zh) return '📦';
  const pk = presetKeyForZh(zh);
  if (pk) return INGREDIENT_PRESETS.find(x => x.key === pk).emoji;
  const d = ZH_TO_ID[zh];
  return d && d.emoji ? d.emoji : '📦';
}

/* ---------- Node 环境下导出，浏览器里直接是全局变量 ---------- */
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    INGREDIENT_PRESETS, ALWAYS_HAVE, ALLERGENS, RECIPES, ZH_TO_ID, ZH_ALIAS,
    scaledQty, formatQtyId, renderStepId, formatQtyZh, renderStepZh,
    presetKeyForZh, customEmoji,
  };
}
